WG\OpenIdUserBundle\Entity\Group:
    type: mappedSuperclass
    fields:
        name:
            type: string
            length: 128
        slug:
            type: string
            length: 128
            unique: true
            gedmo:
                slug:
                    fields:
                        - name
        roles:
            type: array
        updatedAt:
            column: updated_at
            type: datetime
            gedmo:
                timestampable:
                    on: update
        createdAt:
            column: created_at
            type: datetime
            gedmo:
                timestampable:
                    on: create