WG\OpenIdUserBundle\Entity\UserIdentity:
    type: mappedSuperclass
    fields:
        updatedAt:
            name: updated_at
            type: datetime
            gedmo:
                timestampable:
                    on: update
        createdAt:
            name: created_at
            type: datetime
            gedmo:
                timestampable:
                    on: create