WG\OpenIdUserBundle\Entity\User:
    type: entity
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    oneToMany:
        identities:
            targetEntity: UserIdentity
            mappedBy: user
    fields:
        username:
            type: string
            length: 128
        slug:
            type: string
            length: 128
            unique: true
            gedmo:
                slug:
                    fields:
                        - username
        email:
            type: string
            length: 255
        requestedEmail:
            name: requested_email
            type: string
            length: 255
        roles:
            type: array
        enabled:
            type: boolean
        locked:
            type: boolean
        lastLogin:
            name: last_login
            type: datetime
        updatedAt:
            name: updated_at
            type: datetime
            gedmo:
                timestampable:
                    on: update
        createdAt:
            name: created_at
            type: datetime
            gedmo:
                timestampable:
                    on: create