WG\OpenIdUserBundle\Entity\UserIdentity:
    type: mappedSuperclass
    fields:
        identity:
            type: string
            length: 255
        attributes:
            type: array
        updatedAt:
            column: updated_at
            type: datetime
            gedmo:
                timestampable:
                    on: update
        createdAt:
            column: created_at
            type: datetime
            gedmo:
                timestampable:
                    on: create