WG\OpenIdUserBundle\Entity\User:
    type: mappedSuperclass
    fields:
        username:
            type: string
            length: 128
        slug:
            type: string
            length: 128
            unique: true
            gedmo:
                slug:
                    fields:
                        - username
        email:
            type: string
            length: 255
        requestedEmail:
            column: requested_email
            type: string
            length: 255
        roles:
            type: array
        enabled:
            type: boolean
        locked:
            type: boolean
        lastLogin:
            column: last_login
            type: datetime
        updatedAt:
            column: updated_at
            type: datetime
            gedmo:
                timestampable:
                    on: update
        createdAt:
            column: created_at
            type: datetime
            gedmo:
                timestampable:
                    on: create