wg_open_id_user:
    db_driver: %wg_openid.db_driver%
fos_user:
    db_driver: %wg_openid.db_driver%
    firewall_name: %wg_openid.fos_user.firewall_name%
    user_class: %wg_openid.fos_user.user_class%
    group:
        group_class: %wg_openid.fos_user.group_class%
    service:
        user_manager: wg.openid.user_manager.identity
fp_open_id:
    db_driver: %wg_openid.db_driver%
    identity_class: %wg_openid.fp_openid.identity_class%