
# FOS User Bundle Configuration
fos_user:
    db_driver: orm
    user_class: WG\OpenIdUserBundle\Entity\User
    service:
        user_manager: wg.openid.user_manager
    group:
        group_class:  WG\OpenIdUserBundle\Entity\Group

# FP OpenID Bundle Configuration
fp_open_id:
    db_driver: orm
    identity_class: WG\OpenIdUserBundle\Entity\UserIdentity

# Stof/Gedmo Doctrine Extensions config
stof_doctrine_extensions:
    orm:
        default:
            timestampable: true
            sluggable: true
            sortable: true