services:
    wg.openid.user_manager.identity:
        class:  WG\OpenIdUserBundle\Model\UserManager
        arguments:
            - '@fp_openid.identity_manager'
            - '@fos_user.document_manager'
            - %fos_user.model.user.class%
