parameters:
    wg.openid.authentication_success_listener.class:  WG\OpenIdUserBundle\Listener\AuthenticatedEventListener

services:
    wg.openid.authentication_success_listener:
        class:  %wg.openid.authentication_success_listener.class%
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: kernel.event_listener, event: security.authentication.success, method: onAuthenticationSuccess }
